{{- if .Values.services.qbittorrent.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: default
  labels:
    app.kubernetes.io/name: qbittorrent
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.services.qbittorrent.ports.http }}
      targetPort: http
      protocol: TCP
    - name: p2p
      port: {{ .Values.services.qbittorrent.ports.p2p }}
      targetPort: p2p
      protocol: TCP
    - name: p2pudp
      port: {{ .Values.services.qbittorrent.ports.p2pudp }}
      targetPort: p2p
      protocol: UDP
  selector:
    app.kubernetes.io/name: qbittorrent
{{- end }}
