{{- if .Values.services.qbittorrent.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: default
  labels:
    app.kubernetes.io/name: qbittorrent
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: p2p
      port: 6881
      targetPort: p2p
      protocol: TCP
    - name: p2p-udp
      port: 6881
      targetPort: p2p
      protocol: UDP
  selector:
    app.kubernetes.io/name: qbittorrent
{{- end }}
