{{- if .Values.services.changedetectionio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: changedetectionio
  namespace: default
  labels:
    app.kubernetes.io/name: changedetectionio
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: changedetectionio
{{- end }}