{{- if .Values.services.plex.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: default
  labels:
    app.kubernetes.io/name: plex
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 32400
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: plex
{{- end }}
