apiVersion: apps/v1
kind: Deployment
metadata:
  name: autobrr
  namespace: default
  labels:
    app.kubernetes.io/name: autobrr
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: autobrr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: autobrr
    spec:
      containers:
        - name: autobrr
          image: "ghcr.io/autobrr/autobrr:{{ .Values.images.autobrr }}"
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York" 
          ports:
            - name: http
              containerPort: 7474
              protocol: TCP
          volumeMounts:
            - name: autobrr-config
              mountPath: /config
            
      volumes:
        - name: autobrr-config
          hostPath:
            path: "{{ .Values.autobrr.config }}"
            type: Directory
