{{- if .Values.services.autobrr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: autobrr
  namespace: default
  labels:
    app.kubernetes.io/name: autobrr
spec:
  type: ClusterIP
  ports:
    - port: 7474
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: autobrr
{{- end}}