# Original: https://github.com/nestjs/nest/blob/master/.github/ISSUE_TEMPLATE/Feature_request.yml
name: "\U0001F680 Service Request"
description: "I have a suggestion for a new service \U0001F63B!"
labels: ['enhancement', 'needs triage']
body:
  - type: dropdown
    id: functionality
    attributes:
      label: Does this service add new functionality?
      multiple: false
      options:
        - 'New functionality'
        - 'Alternative to existing service'
        - 'Replace existing service'

  - type: input
    id: service
    attributes:
      label: 'Service name'
      description: 'What is the name of the service?'
      placeholder: 'e.g. "plex"'
    validations:
      required: true

  - type: textarea
    id: image
    attributes:
      label: 'Image'
      description: 'What is the name of the image?'
      placeholder: 'e.g. "linuxserver/plex"'
    validations: 
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: 'Description'
      description: 'What does the service do?'
      placeholder: 'e.g. "Plex organizes video, music and photos from personal media libraries and streams them to smart TVs, streaming boxes and mobile devices."'
    validations: 
      required: true
  
  - type: textarea
    id: additional
    attributes:
      label: 'Additional information'
      description: 'Any additional information?'
      placeholder: 'e.g. "Plex is a client-server media player system and software suite comprising two main components. The Plex Media Server desktop application runs on Windows, macOS, and Linux-compatibles including some types of NAS devices. The server desktop application organizes video, audio, and photos from a user''s collections and from online services, enabling the players to access and stream the contents. There are also official clients available for mobile devices, smart TVs, and streaming boxes, a web app, and Plex Home Theater (no longer maintained), as well as many third-party alternatives."'
    validations:
      required: true
