{{- if .Values.services.selenium.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium
  namespace: default
  labels:
    app.kubernetes.io/name: selenium
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.selenium.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: selenium
  template:
    metadata:
      labels:
        app.kubernetes.io/name: selenium
    spec:
      containers:
        - name: selenium
          image: "{{ .Values.services.selenium.image.repository }}:{{ .Values.services.selenium.image.tag }}"
          imagePullPolicy: {{ .Values.services.selenium.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /wd/hub/status
              port: 4444
            initialDelaySeconds: 30
            timeoutSeconds: 5
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "{{ .Values.common.tz }}"
          ports:
            - name: selenium
              containerPort: 4444
              protocol: TCP
            - name: devtools
              containerPort: 7900
              protocol: TCP
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm

      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.services.selenium.shmSize }}
{{- end }}
