apiVersion: apps/v1
kind: Deployment
metadata:
  name: thelounge
  namespace: default
  labels:
    app.kubernetes.io/name: thelounge
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: thelounge
  template:
    metadata:
      labels:
        app.kubernetes.io/name: thelounge
    spec:
      containers:
        - name: thelounge
          image: "lscr.io/linuxserver/thelounge:{{ .Values.images.thelounge }}"
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York" 
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          volumeMounts:
            - name: thelounge-config
              mountPath: /var/opt/thelounge
            
      volumes:
        - name: thelounge-config
          hostPath:
            path: "{{ .Values.thelounge.config }}"
            type: Directory
