apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/homepage/configmap.yaml") . | sha256sum}}
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      initContainers:
      - name: init-config
        image: busybox
        command: ['sh', '-c', 'cp /homepage-config/* /config-working-dir/']
        volumeMounts:
        - name: homepage-config
          mountPath: /homepage-config
        - name: config-working-dir
          mountPath: /config-working-dir
      containers:
        - name: homepage
          image: ghcr.io/benphelps/homepage:{{ .Values.images.homepage }}
          imagePullPolicy: Always
          env:
            - name: TZ
              value: "America/New_York"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: config-working-dir
              mountPath: /app/config
            - name: logs
              mountPath: /app/config/logs
      volumes:
        - name: homepage-config
          configMap:
            name: homepage
        - name: logs
          emptyDir: {}
        - name: config-working-dir
          emptyDir: {}