{{- if .Values.services.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.services.nginx.ports.http }}
      targetPort: {{ .Values.services.nginx.ports.http }}
    - name: https
      protocol: TCP
      port: {{ .Values.services.nginx.ports.https }}
      targetPort: {{ .Values.services.nginx.ports.https }}
    - name: plex
      protocol: TCP
      port: {{ .Values.services.plex.ports.http }}
      targetPort: {{ .Values.services.plex.ports.http }}
  selector:
    app: nginx
{{- end }}
