{{- if .Values.services.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: plex
      protocol: TCP
      port: 32400
      targetPort: 32400
  selector:
    app: nginx
{{- end }}
