{{- if .Values.services.tautulli.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: tautulli
  namespace: default
  labels:
    app.kubernetes.io/name: tautulli
spec:
  type: ClusterIP
  ports:
    - port: 8181
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: tautulli
{{- end }}
