{{- if .Values.services.sonarr.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: default
  labels:
    app.kubernetes.io/name: sonarr
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.sonarr.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sonarr
    spec:
      containers:
        - name: sonarr
          image: "{{ .Values.services.sonarr.image.repository }}:{{ .Values.services.sonarr.image.tag }}"
          imagePullPolicy: {{ .Values.services.sonarr.image.pullPolicy }}
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "{{ .Values.common.tz }}"
          ports:
            - name: http
              containerPort: 8989
              protocol: TCP
          volumeMounts:
            - name: sonarr-config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: tv
              mountPath: /tv

      volumes:
        - name: sonarr-config
          hostPath:
            path: "{{ .Values.services.sonarr.config }}"
            type: Directory
        - name: downloads
          hostPath:
            path: "{{ .Values.services.qbittorrent.downloads }}"
            type: Directory
        - name: tv
          hostPath:
            path: "{{ .Values.services.plex.library.tv }}"
            type: Directory
{{- end }}
