apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: default
  labels:
    app.kubernetes.io/name: sonarr
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sonarr
    spec:
      containers:
        - name: sonarr
          image: "lscr.io/linuxserver/sonarr:{{ .Values.images.sonarr }}"
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York" 
          ports:
            - name: http
              containerPort: 8989
              protocol: TCP
          volumeMounts:
            - name: sonarr-config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: tv
              mountPath: /tv
            
      volumes:
        - name: sonarr-config
          hostPath:
            path: "{{ .Values.sonarr.config }}"
            type: Directory
        - name: downloads
          hostPath:
            path: "{{ .Values.qbittorrent.downloads }}"
            type: Directory
        - name: tv
          hostPath:
            path: "{{ .Values.plex.library.tv }}"
            type: Directory            