apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: default
  labels:
    app.kubernetes.io/name: radarr
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: radarr
    spec:
      containers:
        - name: radarr
          image: "{{ .Values.services.radarr.image.repository }}:{{ .Values.services.radarr.image.tag }}"
          imagePullPolicy: {{ .Values.services.radarr.image.pullPolicy }}
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "{{ .Values.common.tz }}"
          ports:
            - name: http
              containerPort: 7878
              protocol: TCP
          volumeMounts:
            - name: radarr-config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: movies
              mountPath: /movies

      volumes:
        - name: radarr-config
          hostPath:
            path: "{{ .Values.services.radarr.config }}"
            type: Directory
        - name: downloads
          hostPath:
            path: "{{ .Values.services.qbittorrent.downloads }}"
            type: Directory
        - name: movies
          hostPath:
            path: "{{ .Values.services.plex.library.movies }}"
            type: Directory
