{{- if .Values.services.radarr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: default
  labels:
    app.kubernetes.io/name: radarr
spec:
  type: ClusterIP
  ports:
    - port: 7878
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: radarr
{{- end }}
