{{- if .Values.services.playwright.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: playwright
  namespace: default
  labels:
    app.kubernetes.io/name: playwright
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: playwright
{{- end }}