{{- if .Values.services.kavita.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kavita
  namespace: default
  labels:
    app.kubernetes.io/name: kavita
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.services.kavita.ports.http }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: kavita
{{- end }}