apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: default
  labels:
    app.kubernetes.io/name: sabnzbd
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: sabnzbd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sabnzbd
    spec:
      containers:
        - name: sabnzbd
          image: "lscr.io/linuxserver/sabnzbd:{{ .Values.images.sabnzbd }}"
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York" 
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: sabnzbd-config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: sabnzbd-config
          hostPath:
            path: "{{ .Values.sabnzbd.config }}"
            type: Directory
        - name: downloads
          hostPath:
            path: "{{ .Values.qbittorrent.downloads }}"
            type: Directory
