{{- if .Values.services.jackett.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  namespace: default
  labels:
    app.kubernetes.io/name: jackett
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.jackett.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: jackett
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jackett
    spec:
      containers:
        - name: jackett
          image: "{{ .Values.services.jackett.image.repository }}:{{ .Values.services.jackett.image.tag }}"
          imagePullPolicy: {{ .Values.services.jackett.image.pullPolicy }}
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "{{ .Values.common.tz }}"
          ports:
            - name: http
              containerPort: 9117
              protocol: TCP
          volumeMounts:
            - name: jackett-config
              mountPath: /config
            - name: downloads
              mountPath: /downloads

      volumes:
        - name: jackett-config
          hostPath:
            path: "{{ .Values.services.jackett.config }}"
            type: Directory
        - name: downloads
          hostPath:
            path: "{{ .Values.services.qbittorrent.downloads }}"
            type: Directory
{{- end }}