{{- if .Values.services.jackett.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: jackett
  namespace: default
  labels:
    app.kubernetes.io/name: jackett
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.services.jackett.ports.http }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: jackett
{{- end }}